Repository keras-team/keras-hub, pull requests merged in 2024-02, with the labels that each got.

#1429 Add a Causal LM model for Mistral
  keras_nlp/models/__init__.py
  keras_nlp/models/mistral/mistral_attention.py
  keras_nlp/models/mistral/mistral_causal_lm.py
  keras_nlp/models/mistral/mistral_causal_lm_preprocessor.py
  keras_nlp/models/mistral/mistral_causal_lm_preprocessor_test.py
  keras_nlp/models/mistral/mistral_causal_lm_test.py
  keras_nlp/models/mistral/mistral_transformer_decoder.py
Labels: enhancement

#1436 Add 7B presets for Mistral
  keras_nlp/models/mistral/mistral_backbone.py
  keras_nlp/models/mistral/mistral_backbone_test.py
  keras_nlp/models/mistral/mistral_causal_lm.py
  keras_nlp/models/mistral/mistral_causal_lm_preprocessor.py
  keras_nlp/models/mistral/mistral_causal_lm_preprocessor_test.py
  keras_nlp/models/mistral/mistral_preprocessor.py
  keras_nlp/models/mistral/mistral_preprocessor_test.py
  keras_nlp/models/mistral/mistral_presets.py
  keras_nlp/models/mistral/mistral_tokenizer.py
  keras_nlp/models/mistral/mistral_tokenizer_test.py
  tools/checkpoint_conversion/convert_mistral_checkpoints.py
Labels: enhancement

#1470 Add an annotation to tests that need kaggle auth
  keras_nlp/conftest.py
  keras_nlp/models/gemma/gemma_backbone_test.py
  keras_nlp/models/gemma/gemma_causal_lm_preprocessor_test.py
  keras_nlp/models/gemma/gemma_causal_lm_test.py
  keras_nlp/models/gemma/gemma_preprocessor_test.py
  keras_nlp/models/gemma/gemma_tokenizer_test.py
Labels: kokoro:force-run

#1460 Fix Mistral memory consumption with JAX and default dtype bug
  keras_nlp/models/mistral/mistral_causal_lm.py
  keras_nlp/models/mistral/mistral_presets.py
  tools/checkpoint_conversion/convert_mistral_checkpoints.py
Labels: bug
